name: Tests

on: 
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
       
      - name: Install ansible-test
        run: |
          python -m pip install --upgrade pip
          pip install ansible-test==1.0.1
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.12
          testing-type: sanity
          test-deps: >-
            ansible.netcommon
            ansible.utils
#       - name: Perform Unit testing with ansible-test
#         uses: ansible-community/ansible-test-gh-action@release/v1
#         with:
#           ansible-core-version: stable-2.12
#           testing-type: units
#           test-deps: >-
#             ansible.netcommon
#             ansible.utils
      - name: Install tox
        run: pip install tox
      - name: Run tox on python version from matrix
        run: tox -e py
